version = 0.1

[qa.global.parameters]
stack_name = "duitama-taxi-pricing-qa"

[qa.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
s3_prefix = "duitama-taxi-pricing-qa"
resolve_s3 = true
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "NodeEnv=qa CacheEnabled=false CacheTtl=0"

[staging.global.parameters]
stack_name = "duitama-taxi-pricing-staging"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
s3_prefix = "duitama-taxi-pricing-staging"
resolve_s3 = true
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "NodeEnv=staging CacheEnabled=false CacheTtl=0"

[production.global.parameters]
stack_name = "duitama-taxi-pricing-production"

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
s3_prefix = "duitama-taxi-pricing-production"
resolve_s3 = true
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "NodeEnv=production CacheEnabled=true CacheTtl=600"
